### ISSUE TITLE
How can I hide the entry button?

### ISSUE THREAD

**Issue by msynk** [liriliri/eruda#484]
I want to hide the default entry button that conflicts with my app's UI and will show/hide Eruda using the API.

how can I initialize Eruda without showing its default button?

I've read the docs and couldn't find anything. the workaround I've come up so far is like this:

```css
.eruda-entry-btn {
    display: none !important;
}
```

```js
eruda.init({ useShadowDom: false });
```
