### ISSUE TITLE
Sources 标签代码浏览器会将换行的代码计为多行

### ISSUE THREAD

**Issue by UncleBill** [liriliri/eruda#53]
以下是两个截图

![image](https://user-images.githubusercontent.com/1141198/35785149-2764da10-0a59-11e8-8ce5-f38bca633a03.png)
![image](https://user-images.githubusercontent.com/1141198/35785209-b925b19a-0a59-11e8-94f6-6d00097b8aa5.png)

—— 感谢维护！

**Comment by surunzi** [comment]
我这边看长度超过屏幕是不会折叠的，版本是多少？换个浏览器或者换个页面有没有同样的问题？

**Comment by UncleBill** [comment]
我用的http://cdn.jsdelivr.net/npm/eruda
版本是 1.4.2

**Comment by UncleBill** [comment]
@surunzi  是我这边的样式影响了。
```css
pre {
    white-space: pre-wrap;
}
```
建议`eruda`加上
```css
.eruda-dev-tools .eruda-tools .eruda-sources table.eruda-code .eruda-code-line {
    white-space: pre;
}
```
