### ISSUE TITLE
对于source面板下不能长按弹出复制的疑惑

### ISSUE THREAD

**Issue by fa-ge** [liriliri/eruda#71]
经常会出现手机出现一个请求有问题，需要把request payload复制出来发给后端。source面板下不能弹出复制感觉会很麻烦。主要起作用的这段css。

```css
.eruda-container * {
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
    pointer-events: all;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
    -webkit-tap-highlight-color: transparent;
    -webkit-text-size-adjust: none;
}
```

**Comment by surunzi** [comment]
下个版本会允许复制，目前自己可以直接用 css 覆盖掉样式：
```css
.eruda-container .eruda-sources * {
    -webkit-user-select: text;
    -moz-user-select: text;
    -ms-user-select: text;
    user-select: text;
}
```
